#!/usr/bin/env bash
# ============================================================================
# SteamTools — slsteam-moon auto-installer (Linux)
#
# One-liner install:
#   curl -fsSL https://www.steamtools.app/sl-fix.sh | bash
#
# What it does:
#   1. Downloads the latest slsteam-moon release from GitHub
#   2. Extracts SteamTools.so + library-inject.so to ~/.local/share/SteamTools/
#   3. Creates a Steam wrapper with LD_AUDIT injection
#   4. Creates a .desktop entry for Steam (with injection)
# ============================================================================
set -euo pipefail

REPO="swwayps/slsteam-moon"
INSTALL_DIR="$HOME/.local/share/SteamTools"
WRAPPER_DIR="$INSTALL_DIR/path"

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { printf "${BOLD}${GREEN}✓${NC} %s\n" "$1"; }
warn()  { printf "${BOLD}${YELLOW}!${NC} %s\n" "$1"; }
error() { printf "${BOLD}${RED}✗${NC} %s\n" "$1" >&2; exit 1; }

# ── Preflight ──────────────────────────────────────────────────────────────
command -v curl >/dev/null || error "curl is required. Install it with your package manager."
command -v unzip >/dev/null || error "unzip is required. Install it with your package manager."

if [ -f "$WRAPPER_DIR/steam" ]; then
    info "slsteam-moon is already installed at $WRAPPER_DIR/steam"
    echo "  To reinstall, remove $INSTALL_DIR first."
    exit 0
fi

# ── Find latest release asset ──────────────────────────────────────────────
info "Finding latest slsteam-moon release..."

API_URL="https://api.github.com/repos/$REPO/releases/latest"
RELEASE_JSON=$(curl -fsSL "$API_URL" \
    -H "Accept: application/vnd.github.v3+json" \
    -H "User-Agent: SteamTools-Linux") \
    || error "Failed to query GitHub API (rate limit?). Try again later."

ASSET_URL=$(echo "$RELEASE_JSON" | grep -o '"browser_download_url": *"[^"]*slsteam-moon-linux-[^"]*\.zip"' | head -1 | cut -d'"' -f4)

if [ -z "$ASSET_URL" ]; then
    # Fallback: try generic name
    ASSET_URL="https://github.com/$REPO/releases/latest/download/slsteam-moon-linux.zip"
fi

# ── Download & extract ─────────────────────────────────────────────────────
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

info "Downloading from: $ASSET_URL"
curl -fSL -o "$TMPDIR/slsteam-moon.zip" "$ASSET_URL" \
    || error "Download failed. Check your connection."

unzip -qo "$TMPDIR/slsteam-moon.zip" -d "$TMPDIR/extracted" \
    || error "Failed to extract zip."

# ── Find extracted directory ───────────────────────────────────────────────
EXTRACTED="$TMPDIR/extracted"
for d in "$EXTRACTED"/slsteam-moon*; do
    [ -d "$d" ] && EXTRACTED="$d" && break
done

# ── Install ────────────────────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR" "$WRAPPER_DIR"

# Copy binaries
cp -f "$EXTRACTED"/*.so "$INSTALL_DIR/" 2>/dev/null || true
cp -f "$EXTRACTED"/library-inject.so "$INSTALL_DIR/" 2>/dev/null || true
cp -f "$EXTRACTED"/setup.sh "$INSTALL_DIR/" 2>/dev/null || true
cp -f "$EXTRACTED"/autofix.sh "$INSTALL_DIR/" 2>/dev/null || true

# Find the main .so (SteamTools.so or libsteamclient.so or SLSsteam.so)
LIB_PATH=""
for name in SteamTools.so libsteamclient.so SLSsteam.so steamclient.so; do
    if [ -f "$INSTALL_DIR/$name" ]; then
        LIB_PATH="$INSTALL_DIR/$name"
        break
    fi
done

# If not in root, search subdirs
if [ -z "$LIB_PATH" ]; then
    LIB_PATH=$(find "$EXTRACTED" -name "*.so" -type f | head -1)
    if [ -n "$LIB_PATH" ]; then
        cp -f "$LIB_PATH" "$INSTALL_DIR/"
        LIB_PATH="$INSTALL_DIR/$(basename "$LIB_PATH")"
    fi
fi

[ -z "$LIB_PATH" ] && error "Could not find the main .so library in the release."

# ── Create Steam wrapper ───────────────────────────────────────────────────
cat > "$WRAPPER_DIR/steam" << 'WRAPPER'
#!/bin/bash
# slsteam-moon Steam wrapper (auto-generated by SteamTools)

INSTALL_DIR="$HOME/.local/share/SteamTools"

# Find real Steam (skip ourselves)
find_real_steam() {
    for c in /usr/bin/steam /usr/games/steam /usr/local/bin/steam /bin/steam; do
        if [ -x "$c" ] && [ "$(readlink -f "$c" 2>/dev/null)" != "$(readlink -f "$0" 2>/dev/null)" ]; then
            echo "$c"
            return
        fi
    done
    local IFS=':'
    for dir in $PATH; do
        [ "$dir" = "$INSTALL_DIR/path" ] && continue
        if [ -x "$dir/steam" ]; then
            echo "$dir/steam"
            return
        fi
    done
    echo "/usr/bin/steam"
}

REAL_STEAM="$(find_real_steam)"

# Set LD_AUDIT for slsteam-moon injection
for lib in "$INSTALL_DIR"/*.so; do
    [ -f "$lib" ] && export LD_AUDIT="$lib" && break
done

exec "$REAL_STEAM" "$@"
WRAPPER
chmod +x "$WRAPPER_DIR/steam"

# ── Create .desktop entry ──────────────────────────────────────────────────
DESKTOP_DIR="$HOME/.local/share/applications"
mkdir -p "$DESKTOP_DIR"

cat > "$DESKTOP_DIR/steam-slsteam.desktop" << DESKTOP
[Desktop Entry]
Name=Steam (slsteam-moon)
Comment=Steam with slsteam-moon mod loader
Exec=$WRAPPER_DIR/steam %u
Icon=steam
Terminal=false
Type=Application
Categories=Game;
DESKTOP

# ── Done ───────────────────────────────────────────────────────────────────
echo ""
info "slsteam-moon installed successfully!"
echo "  Library: $LIB_PATH"
echo "  Wrapper: $WRAPPER_DIR/steam"
echo "  Desktop: $DESKTOP_DIR/steam-slsteam.desktop"
echo ""
warn "Launch Steam from the new 'Steam (slsteam-moon)' desktop entry,"
echo "  or run: $WRAPPER_DIR/steam"
